# frozen_string_literal: true

source "https://rubygems.org"
ruby "3.2.2"

gem "activerecord", "~> 6.1"
gem "pg", "~> 1.2"
gem "sinatra", "~> 2.1"
gem "sinatra-activerecord", "~> 2.0"
gem "puma", "~> 5.0"
gem 'puma-metrics'

group :development do
  gem "rubocop", "~> 1.22", require: false
  gem "rubocop-shopify", "~> 2.0", require: false
end
